name: Publish docker image
on: 
  - push
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: docker-compose build
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io # optional
          username: NokiDev # optional
          password: ${{secrets.PAT}} # optional
      - run: docker-compose push
