name: Publish docker image
on: 
  - push
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: docker-compose build
      - run: export CR_PAT=${{secrets.PAT}}
      - run: echo $CR_PAT | docker login ghcr.io -u NokiDev --password-stdin
      - run: docker-compose push
